### ISSUE TITLE
Editing pane is just black in Safari

### ISSUE THREAD

**Issue by wrs** [ishubin/schemio#712] opened 2024-12-17 19:59 UTC
Editing works fine in Chrome but in Safari the editing pane is just solid black. I can still select and operate on objects, I just can't see them. Screenshot attached of editing the Nginx example.

MacOS 15.1.1 (24B2091)
Safari Version 18.1.1 (20619.2.8.11.12)

<img width="1331" alt="image" src="https://github.com/user-attachments/assets/6a4847c6-1a78-46ba-9ee3-4b53737b1b8d" />

**Comment by ishubin** [comment] 2024-12-18 05:37
Thank you very much for reporting that! I just released a fix. I overlooked that I forgot to properly clean the code after I have been experimenting with SVG filters and it turns out that Safari is not as forgiving as Chrome. Could you please try again?

**Comment by ishubin** [comment] 2024-12-22 19:17
I have tested it in Safari and I can't reproduce the issue anymore, so closing it

**Closed by ishubin** 2024-12-22 19:17 UTC

**Comment by wrs** [comment] 2024-12-31 00:21
Confirming this works now for me too, thanks!
